spring:
  datasource:
    url: jdbc:h2:mem:recipedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

recipe:
  encryption:
    secret: secret-key-12345
    algorithm: AES

security:
  jwt:
    token:
      expire-length: 3600000
      secret-key: secrect-key-for-jwt